### PR TITLE
Fix workflows page not properly filtering workflows

### LINKED ISSUE #57: Workflows page status dropdown not filtering workflows properly
When viewing workflows on the Temporal Web portal, if one changes the status dropdown to "Completed", workflows with status Completed do not show up.

Testing with Temporal v0.26.0

### PR DESCRIPTION
**Pull request by feedmeapples**
Fixes #57 Workflows page status dropdown not filtering workflows properly bug

### CODE REVIEW

File: client/routes/namespace/workflow-list.vue [hunk 1]
```diff
@@ -130,12 +130,15 @@ export default pagedGrid({
       statuses: [
         { value: 'OPEN', label: 'Open' },
```
Comment (alexshtin) [inline client/routes/namespace/workflow-list.vue:131]: I would rename this to `RUNNING` for consistency with `WORKFLOW_EXECUTION_STATUS_RUNNING` (if it makes sense).

Comment (feedmeapples) [reply client/routes/namespace/workflow-list.vue:131]: in general I agree, in this case we should also update the API and remove explicit ListOpenWorkflowExecutions command (as well as ListClosedWorkflowExecutions ). Instead unify into a single endpoint ListWorkflowExecutions with a status param
